### ISSUE TITLE
Unable to find type `[Microsoft.UpdateServices.Internal.BaseApi.Update]`

### ISSUE THREAD

**Issue by Wolvverine** [ralish/PSWsusSpringClean#3]
> Invoke-WsusSpringClean -DeclineArchitectures arm64

```
Unable to find type [Microsoft.UpdateServices.Internal.BaseApi.Update].
At .\PSWsusSpringClean\PSWsusSpringClean.psm1:131 char:25
+ ... utType([Void], [Microsoft.UpdateServices.Internal.BaseApi.Update[]])]
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Updat....BaseApi.Update:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by ralish** [comment]
That type is provided by the `UpdateServices` module. Is it listed in the output of `Get-Module`? If not, import it via `Import-Module UpdateServices` and check if you still get the error if you run the command again. It should be imported automatically as it is listed as a dependency in the module manifest.

Let's see if we can get it imported and the `Invoke-WsusSpringClean` command working, and from there we can figure out why the error appeared at all.

**Comment by ralish** [comment]
@Wolvverine Any luck with getting the above?

**Comment by ralish** [comment]
Closing as I can't reproduce the issue and no response from the reporter.
